version: "3.7"
services:
  scrabble-ui:
    image: scrabble-ui
    container_name: scrabble-ui
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    environment:
      - API_URL=http://localhost:4090/graphql
networks:
  default:
    external:
      name: scrabble